server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
        #while stratign the application it all was check the schema.sql fiel excute the all tbales if table present in the database then not excute . which ever not there it automatically excute the tbales

  config:
    import: "optional:configserver:http:localhost:8071/"


#from accouts yml file we activing profile the prod and calling the service config with url. regraless name of the config service we have use the same configserver in url


management:
  endpoints:
    web:
      exposure:
        insclude: "*"


      #enableing the spring activetors to use all apis in the application